services:
  mongo:
    restart: always
    image: mongo
    #command: mongod --replSet rs0
    expose:
      - 27017:27017
    #networks:
      #- mongo-cluster
    volumes:
      - ./create-schema.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo2:
    image: mongo
    #command: mongod --replSet rs0
    expose:
      - 27018:27018
    #networks:
      #- mongo-cluster
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    #networks:
      #- mongo-cluster

#networks:
  #mongo-cluster:
    #driver: bridge
